Do not allow missing return in function returning non-void.
In order to avoid mistakes.

    error: no return statement in function returning non-void